# Generated by Django 6.0 on 2025-12-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_remove_signer_unnecessary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='analysis_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='model_used',
            field=models.CharField(default='spacy', max_length=100),
        ),
    ]
